version: "3.8"

x-build-e2e: &x-build-e2e
  image: primo-customization-cdn-e2e
  build:
    context: ./
    dockerfile: e2e/Dockerfile
    cache_from:
      - primo-customization-cdn-e2e

x-environment: &x-environment
  VIEW: ${VIEW}

services:
  cdn-server:
    image: primo-customization-cdn-cdn-server
    build:
      dockerfile: Dockerfile.cdn-server
    ports:
      - "3000:3000"
    networks:
      - primo-customization-cdn-net
    # volumes:
    #   - ./primo-customization:/app/cdn/primo-customization
  #  NOTE: This service name `primo-explore-devenv` is hard-coded into the view packages' `getCdn()` code.
  #        https://github.com/NYULibraries/primo-customization/blob/ffadff7421a150d84271bcee3bcb9f37e6ccf678/docker-compose.yml?#L115-#L116
  #        If changing this name, make sure to update that reference.
  primo-explore-devenv:
    image: quay.io/nyulibraries/primo-customization-devenv:main
    ports:
      - "8003:8003"
    depends_on:
      - cdn-server
    environment:
      <<: *x-environment
    networks:
      primo-customization-cdn-net:
        aliases:
          - devenv

  e2e:
    <<: *x-build-e2e
    depends_on:
      - primo-explore-devenv
    environment:
      <<: *x-environment
      PLAYWRIGHT_BASE_URL: http://primo-explore-devenv:8003
    # https://playwright.dev/docs/ci#docker
    # CI configurations > Docker
    # "Using --ipc=host is also recommended when using Chromium. Without it Chromium can run out of memory and crash."
    ipc: host
    networks:
      - primo-customization-cdn-net
  e2e-update-golden-files:
    <<: *x-build-e2e
    depends_on:
      - primo-explore-devenv
    environment:
      <<: *x-environment
      PLAYWRIGHT_BASE_URL: http://primo-explore-devenv:8003
      UPDATE_GOLDEN_FILES: true
    ipc: host
    networks:
      - primo-customization-cdn-net
    # volumes:
    #   - ./e2e/tests/golden:/e2e/tests/golden

  # services for local tls, i.e. for login
  tls:
    image: primo-customization-cdn-tls-nginx
    build:
      dockerfile: Dockerfile.nginx
    ports:
      - "443:443"
    depends_on:
      - devenv-tls
      - cdn-server
    extra_hosts:
      - "nyu.primo.exlibrisgroup.com:216.147.212.109"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
  devenv-tls:
    image: quay.io/nyulibraries/primo-customization-devenv:nyu.primo.exlibrisgroup.com
    depends_on:
      - cdn-server
    extra_hosts:
      - "nyu.primo.exlibrisgroup.com:216.147.212.109"
    environment:
      <<: *x-environment

networks:
  primo-customization-cdn-net:
    driver: bridge
