version: "3.8"

x-build-e2e: &x-build-e2e
  image: primo-customization-cdn-e2e
  build:
    context: ./
    dockerfile: e2e/Dockerfile
    cache_from:
      - primo-customization-cdn-e2e

x-environment: &x-environment
  VIEW: ${VIEW}

services:
  cdn-server:
    image: quay.io/nyulibraries/primo-customization-cdn-server:nyu.primo.exlibrisgroup.com
    ports:
      - "3000:3000"
    networks:
      - primo-customization-cdn-net
    # volumes:
    #   - ./primo-customization:/app/cdn/primo-customization
  devenv:
    image: quay.io/nyulibraries/primo-customization-devenv:nyu.primo.exlibrisgroup.com
    ports:
      - "8003:8003"
    depends_on:
      - cdn-server
    environment:
      VIEW: ${VIEW}
    networks:
      - primo-customization-cdn-net
  e2e:
    <<: *x-build-e2e
    depends_on:
      - devenv
    environment:
      <<: *x-environment
      PLAYWRIGHT_BASE_URL: http://devenv:8003/discovery/search
    # https://playwright.dev/docs/ci#docker
    # CI configurations > Docker
    # "Using --ipc=host is also recommended when using Chromium. Without it Chromium can run out of memory and crash."
    ipc: host
    networks:
      - primo-customization-cdn-net
  e2e-update-golden-files:
    <<: *x-build-e2e
    depends_on:
      - devenv
    environment:
      <<: *x-environment
      PLAYWRIGHT_BASE_URL: http://devenv:8003/discovery/search
      UPDATE_GOLDEN_FILES: true
    ipc: host
    networks:
      - primo-customization-cdn-net
    # volumes:
    #   - ./e2e/tests/golden:/e2e/tests/golden

networks:
  primo-customization-cdn-net:
    driver: bridge