FROM quay.io/nyulibraries/nginx:1.21.1-0

USER root
RUN apk update && apk add --no-cache openssl
RUN openssl req -x509 -newkey ec -pkeyopt ec_paramgen_curve:secp384r1 -days 3650 \
  -nodes -keyout nyu.primo.exlibrisgroup.com.key -out nyu.primo.exlibrisgroup.com.crt -subj "/CN=nyu.primo.exlibrisgroup.com" \
  -addext "subjectAltName=DNS:nyu.primo.exlibrisgroup.com,DNS:*.primo.exlibrisgroup.com,IP:10.0.0.1"

#USER nginx
