docker-defaults: &docker-defaults
  docker:
    - image: cimg/base:2023.07
  working_directory: ~/app

asset_sanity_check: &asset_sanity_check
  run:
    name: Asset sanity check
    command: |
      scripts/asset-sanity-check.sh

aws-export: &aws-export
  run:
    name: Export AWS env vars
    command: |
      echo 'export AWS_ACCESS_KEY_ID=${WEB_CDN_AWS_ACCESS_KEY_ID}' >> $BASH_ENV
      echo 'export AWS_SECRET_ACCESS_KEY=${WEB_CDN_AWS_SECRET_ACCESS_KEY}' >> $BASH_ENV
      echo 'export AWS_REGION=us-east-1' >> $BASH_ENV

aws-sync: &aws-sync
  aws-s3/sync:
    from: primo-customization
    to: "${S3_URI}/primo-customization"

version: 2.1
orbs:
  aws-s3: circleci/aws-s3@3.1.1
jobs:
  run-e2e: &run-e2e
    <<: *docker-defaults
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Run tests
          command: |
            docker-compose run e2e
      - run:
          name: Copy test results
          command: |
            mkdir -p test-results
            docker cp "$(docker ps -q -a -f name=app-e2e-run)":/e2e/test-results/. test-results || echo "No test results to copy."
          when: always
      - store_artifacts:
          path: test-results
      - store_test_results:
          path: test-results

  run-e2e-ad-dev:
    <<: [*docker-defaults, *run-e2e]
    environment:
      VIEW: 01NYU_AD-AD_DEV

  run-e2e-ad-prod:
    <<: [*docker-defaults, *run-e2e]
    environment:
      VIEW: 01NYU_AD-AD

  run-e2e-nyhs-dev:
    <<: [*docker-defaults, *run-e2e]
    environment:
      VIEW: 01NYU_NYHS-NYHS_DEV

  run-e2e-nyhs-prod:
    <<: [*docker-defaults, *run-e2e]
    environment:
      VIEW: 01NYU_NYHS-NYHS

  run-e2e-nysid-dev:
    <<: [*docker-defaults, *run-e2e]
    environment:
      VIEW: 01NYU_NYSID-NYSID_DEV

  run-e2e-nysid-prod:
    <<: [*docker-defaults, *run-e2e]
    environment:
      VIEW: 01NYU_NYSID-NYSID

  run-e2e-nyu-dev:
    <<: [*docker-defaults, *run-e2e]
    environment:
      VIEW: 01NYU_INST-NYU_DEV

  run-e2e-nyu-prod:
    <<: [*docker-defaults, *run-e2e]
    environment:
      VIEW: 01NYU_INST-NYU

  run-e2e-nyu-test:
    <<: [*docker-defaults, *run-e2e]
    environment:
      VIEW: 01NYU_INST-TESTWS01

  run-e2e-sh-dev:
    <<: [*docker-defaults, *run-e2e]
    environment:
      VIEW: 01NYU_US-SH_DEV

  run-e2e-sh-prod:
    <<: [*docker-defaults, *run-e2e]
    environment:
      VIEW: 01NYU_US-SH

  deploy_dev:
    <<: *docker-defaults
    steps:
      - checkout
      - setup_remote_docker
      - *asset_sanity_check
      - *aws-export
      - *aws-sync
  deploy_prod:
    <<: *docker-defaults
    steps:
      - checkout
      - setup_remote_docker
      - *asset_sanity_check
      - *aws-export
      - *aws-sync

workflows:
  version: 2.1
  build-and-deploy:
    jobs:
      - run-e2e-ad-dev:
          filters:
            branches:
              ignore: main
      - run-e2e-ad-prod:
          filters:
            branches:
              only: main
      #- run-e2e-nyhs-dev:
      #    filters:
      #      branches:
      #        ignore: main
      #- run-e2e-nyhs-prod:
      #    filters:
      #      branches:
      #        only:
      #          main
      #- run-e2e-nysid-dev:
      #    filters:
      #      branches:
      #        ignore: main
      #- run-e2e-nysid-prod:
      #    filters:
      #      branches:
      #        only: main
      - run-e2e-nyu-dev:
          filters:
            branches:
              ignore: main
      - run-e2e-nyu-prod:
          filters:
            branches:
              only: main
      - run-e2e-nyu-test:
          filters:
            branches:
              ignore: main
      - run-e2e-sh-dev:
          filters:
            branches:
              ignore: main
      - run-e2e-sh-prod:
          filters:
            branches:
              only: main
      - deploy_dev:
          requires:
            - run-e2e-ad-dev
            #- run-e2e-nyhs-dev
            #- run-e2e-nysid-dev
            - run-e2e-nyu-dev
            - run-e2e-nyu-test
            - run-e2e-sh-dev
          context: web-cdn-aws-nyulitsdev
          filters:
            branches:
              only: develop
      - deploy_prod:
          requires:
            - run-e2e-ad-prod
            #- run-e2e-nyhs-prod
            #- run-e2e-nysid-prod
            - run-e2e-nyu-prod
            - run-e2e-sh-prod
          context: web-cdn-aws-nyulits
          filters:
            branches:
              only: main
