docker-defaults: &docker-defaults
  docker:
    - image: cimg/base:2023.07
  working_directory: ~/app

asset_sanity_check: &asset_sanity_check
  run:
    name: Asset sanity check
    command: |
      scripts/asset-sanity-check.sh

aws-export: &aws-export
  run:
    name: Export AWS env vars
    command: |
      echo 'export AWS_ACCESS_KEY_ID=${WEB_CDN_AWS_ACCESS_KEY_ID}' >> $BASH_ENV
      echo 'export AWS_SECRET_ACCESS_KEY=${WEB_CDN_AWS_SECRET_ACCESS_KEY}' >> $BASH_ENV
      echo 'export AWS_REGION=us-east-1' >> $BASH_ENV

aws-sync: &aws-sync
  aws-s3/sync:
    from: primo-customization
    to: "${S3_URI}/primo-customization"

version: 2.1
orbs:
  aws-s3: circleci/aws-s3@3.1.1
jobs:
  run-e2e: &run-e2e
    <<: *docker-defaults
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Run tests
          command: |
            docker-compose run e2e

  run-e2e-nyu-dev:
    <<: *docker-defaults
    environment:
      VIEW: 01NYU_INST-NYU_DEV
    <<: *run-e2e

  run-e2e-nyu-prod:
    <<: *docker-defaults
    environment:
      VIEW: 01NYU_INST-NYU
    <<: *run-e2e

  deploy_dev:
    <<: *docker-defaults
    steps:
      - checkout
      - setup_remote_docker
      - *asset_sanity_check
      - *aws-export
      - *aws-sync
  deploy_prod:
    <<: *docker-defaults
    steps:
      - checkout
      - setup_remote_docker
      - *asset_sanity_check
      - *aws-export
      - *aws-sync

workflows:
  version: 2.1
  build-and-deploy:
    jobs:
      - run-e2e-nyu-dev
      - run-e2e-nyu-prod
      - deploy_dev:
          requires:
            - run-e2e-nyu-dev
            - run-e2e-nyu-prod
          context: web-cdn-aws-nyulitsdev
          filters:
            branches:
              only: develop
      - deploy_prod:
          requires:
            - run-e2e-nyu-dev
            - run-e2e-nyu-prod
          context: web-cdn-aws-nyulits
          filters:
            branches:
              only: main
