docker-defaults: &docker-defaults
  docker:
    - image: cimg/base:2023.07
  working_directory: ~/app

aws-export: &aws-export
  run:
    name: Export AWS env vars
    command: |
      echo 'export AWS_ACCESS_KEY_ID=${WEB_CDN_AWS_ACCESS_KEY_ID}' >> $BASH_ENV
      echo 'export AWS_SECRET_ACCESS_KEY=${WEB_CDN_AWS_SECRET_ACCESS_KEY}' >> $BASH_ENV
      echo 'export AWS_REGION=us-east-1' >> $BASH_ENV

aws-sync: &aws-sync
  aws-cli/setup

version: 2.1
orbs:
  aws-cli: circleci/aws-cli@4.1.1
jobs:

  deploy_dev:
    <<: *docker-defaults
    steps:
      - checkout
      - setup_remote_docker
      - *aws-export
      - *aws-sync

workflows:
  version: 2.1
  build-and-deploy:
    jobs:
      - deploy_dev:
          context: web-cdn-aws-nyulitsdev
          filters:
            branches:
              ignore: main
